-- This code is written for Postgres

-- Teams table
create table rocket_league.teams (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	id varchar(30) not null constraint teams_pk primary key,
	slug varchar(100),
	"name" varchar not null,
	region varchar(10),
	image varchar,
	relevant bool
);

-- Players table
create table rocket_league.players (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	team_id varchar(30),
	id varchar(30) not null constraint players_pk primary key,
	slug varchar(100),
	tag varchar,
	country varchar(10),
	"name" varchar,
	coach bool,
	relevant bool,
	substitute bool
--	constraint players_teams_fk
--		foreign key (team_id)
--			references rocket_league.teams(id)
);

-- Players accounts table
create table rocket_league.players_accounts (
	id serial primary key,
	player_id varchar(30) not null,
	platform varchar(50) not null,
	platform_id varchar(50) not null,
	constraint playeraccount_players_fk
		foreign key (player_id)
			references rocket_league.players(id)
);

-- Events table
create table rocket_league.events (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	id varchar(30) not null constraint events_pk primary key,
	slug varchar not null,
	"name" varchar not null,
	start_date timestamp,
	end_date timestamp,
	region varchar(10),
	"mode" smallint,
	prize_amount int,
	prize_currency varchar(10),
	tier varchar(20),
	image varchar,
	"groups" varchar[]
);
	
-- Events stages table
create table rocket_league.events_stages (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	id int not null,
	"name" varchar not null,
	"format" varchar(20),
	region varchar(10),
	start_date timestamp,
	end_date timestamp,
	liquipedia varchar,
	prize_amount int,
	prize_currency varchar(10),
	qualifier bool,
	lan bool,
	location_venue varchar(100),
	location_city varchar(50),
	location_country varchar(10),
	constraint stages_pk
		primary key (event_id, id),
	constraint stages_events_fk
		foreign key(event_id)
			references rocket_league.events(id)
);


-- Matches table
create table rocket_league.matches (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	stage_id int,
	id varchar(30) not null constraint matches_pk primary key,
	slug varchar not null,
	octane_id int,
	"date" timestamp,
	"format_type" varchar(50),
	"format_length" int,
	blue_games int,
	blue_winner bool,
	blue_team_id varchar(30),
	blue_shots int,
	blue_goals int,
	blue_saves int,
	blue_assists int,
	blue_score int,
	blue_shooting_percentage numeric,
	blue_boost_bpm int,
	blue_boost_bcpm numeric,
	blue_boost_avg_amount numeric,
	blue_boost_amount_collected int,
	blue_boost_amount_stolen int,
	blue_boost_amount_collected_big int,
	blue_boost_amount_stolen_big int,
	blue_boost_amount_collected_small int,
	blue_boost_amount_stolen_small int,
	blue_boost_count_collected_big int,
	blue_boost_count_stolen_big int,
	blue_boost_count_collected_small int,
	blue_boost_count_stolen_small int,
	blue_boost_amount_overfill int,
	blue_boost_amount_overfill_stolen int,
	blue_boost_amount_used_while_supersonic int,
	blue_boost_time_zero_boost numeric,
	blue_boost_time_full_boost numeric,
	blue_boost_time_boost0_to25 numeric,
	blue_boost_time_boost25_to50 numeric,
	blue_boost_time_boost50_to75 numeric,
	blue_boost_time_boost75_to100 numeric,
	blue_movement_total_distance numeric,
	blue_movement_time_supersonic_speed numeric,
	blue_movement_time_boost_speed numeric,
	blue_movement_time_slow_speed numeric,
	blue_movement_time_ground numeric,
	blue_movement_time_low_air numeric,
	blue_movement_time_high_air numeric,
	blue_movement_time_powerslide numeric,
	blue_movement_count_powerslide int,
	blue_positioning_time_defensive_third numeric,
	blue_positioning_time_neutral_third numeric,
	blue_positioning_time_offensive_third numeric,
	blue_positioning_time_defensive_half numeric,
	blue_positioning_time_offensive_half numeric,
	blue_positioning_time_behind_ball numeric,
	blue_positioning_time_infront_ball numeric,
	blue_demo_inflicted int,
	blue_demo_taken int,
	orange_games int,
	orange_winner bool,
	orange_team_id varchar(30),
	orange_shots int,
	orange_goals int,
	orange_saves int,
	orange_assists int,
	orange_score int,
	orange_shooting_percentage numeric,
	orange_boost_bpm int,
	orange_boost_bcpm numeric,
	orange_boost_avg_amount numeric,
	orange_boost_amount_collected int,
	orange_boost_amount_stolen int,
	orange_boost_amount_collected_big int,
	orange_boost_amount_stolen_big int,
	orange_boost_amount_collected_small int,
	orange_boost_amount_stolen_small int,
	orange_boost_count_collected_big int,
	orange_boost_count_stolen_big int,
	orange_boost_count_collected_small int,
	orange_boost_count_stolen_small int,
	orange_boost_amount_overfill int,
	orange_boost_amount_overfill_stolen int,
	orange_boost_amount_used_while_supersonic int,
	orange_boost_time_zero_boost numeric,
	orange_boost_time_full_boost numeric,
	orange_boost_time_boost0_to25 numeric,
	orange_boost_time_boost25_to50 numeric,
	orange_boost_time_boost50_to75 numeric,
	orange_boost_time_boost75_to100 numeric,
	orange_movement_total_distance numeric,
	orange_movement_time_supersonic_speed numeric,
	orange_movement_time_boost_speed numeric,
	orange_movement_time_slow_speed numeric,
	orange_movement_time_ground numeric,
	orange_movement_time_low_air numeric,
	orange_movement_time_high_air numeric,
	orange_movement_time_powerslide numeric,
	orange_movement_count_powerslide int,
	orange_positioning_time_defensive_third numeric,
	orange_positioning_time_neutral_third numeric,
	orange_positioning_time_offensive_third numeric,
	orange_positioning_time_defensive_half numeric,
	orange_positioning_time_offensive_half numeric,
	orange_positioning_time_behind_ball numeric,
	orange_positioning_time_infront_ball numeric,
	orange_demo_inflicted int,
	orange_demo_taken int,
	"number" int,
	reverse_sweep_attempt bool,
	reverse_sweep bool,
	constraint match_event_fk
		foreign key(event_id)
			references rocket_league.events(id)
--	constraint match_stage_fk
--		foreign key(event_id, stage_id)
--			references rocket_league.events_stages(event_id, id)
);


-- Player performance by Match table
create table rocket_league.matches_players (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	stage_id int,
	match_id varchar(30) not null,
	team_id varchar(30),
	color varchar(10) not null,
	id varchar(30)not null,
	shots int,
	goals int,
	saves int,
	assists int,
	score int,
	shooting_percentage numeric,
	advanced_goal_participation numeric,
	advanced_rating numeric,
	boost_bpm int,
	boost_bcpm numeric,
	boost_avg_amount numeric,
	boost_amount_collected int,
	boost_amount_stolen int,
	boost_amount_collected_big int,
	boost_amount_stolen_big int,
	boost_amount_collected_small int,
	boost_amount_stolen_small int,
	boost_count_collected_big int,
	boost_count_stolen_big int,
	boost_count_collected_small int,
	boost_count_stolen_small int,
	boost_amount_overfill int,
	boost_amount_overfill_stolen int,
	boost_amount_used_while_supersonic int,
	boost_time_zero_boost numeric,
	boost_percent_zero_boost numeric,
	boost_time_full_boost numeric,
	boost_percent_full_boost numeric,
	boost_time_boost0_to25 numeric,
	boost_time_boost25_to50 numeric,
	boost_time_boost50_to75 numeric,
	boost_time_boost75_to100 numeric,
	boost_percent_boost0_to25 numeric,
	boost_percent_boost25_to50 numeric,
	boost_percent_boost50_to75 numeric,
	boost_percent_boost75_to100 numeric,
	movement_avg_speed numeric,
	movement_total_distance numeric,
	movement_time_supersonic_speed numeric,
	movement_time_boost_speed numeric,
	movement_time_slow_speed numeric,
	movement_time_ground numeric,
	movement_time_low_air numeric,
	movement_time_high_air numeric,
	movement_time_powerslide numeric,
	movement_count_powerslide int,
	movement_avg_powerslide_duration numeric,
	movement_avg_speed_percentage numeric,
	movement_percent_slow_speed numeric,
	movement_percent_boost_speed numeric,
	movement_percent_supersonic_speed numeric,
	movement_percent_ground numeric,
	movement_percent_low_air numeric,
	movement_percent_high_air numeric,
	positioning_avg_distance_to_ball numeric,
	positioning_avg_distance_to_ball_possession numeric,
	positioning_avg_distance_to_ball_no_possession numeric,
	positioning_avg_distance_to_mates numeric,
	positioning_time_defensive_third numeric,
	positioning_time_neutral_third numeric,
	positioning_time_offensive_third numeric,
	positioning_time_defensive_half numeric,
	positioning_time_offensive_half numeric,
	positioning_time_behind_ball numeric,
	positioning_time_infront_ball numeric,
	positioning_time_most_back numeric,
	positioning_time_most_forward numeric,
	positioning_goals_against_while_last_defender int,
	positioning_time_closest_to_ball numeric,
	positioning_time_farthest_from_ball numeric,
	positioning_percent_defensive_third numeric,
	positioning_percent_offensive_third numeric,
	positioning_percent_neutral_third numeric,
	positioning_percent_defensive_half numeric,
	positioning_percent_offensive_half numeric,
	positioning_percent_behind_ball numeric,
	positioning_percent_infront_ball numeric,
	positioning_percent_most_back numeric,
	positioning_percent_most_forward numeric,
	positioning_percent_closest_to_ball numeric,
	positioning_percent_farthest_from_ball numeric,
	demo_inflicted int,
	demo_taken int,
	player_substitute bool,
	player_coach bool,
	constraint matchplayer_pk
		primary key (match_id, id),
	constraint matchplayer_event_fk
		foreign key(event_id)
			references rocket_league.events(id),
--	constraint matchplayer_stage_fk
--		foreign key(event_id, stage_id)
--			references rocket_league.events_stages(event_id, id),
	constraint matchplayer_match_fk
		foreign key(match_id)
			references rocket_league.matches(id)
);

create table rocket_league.games (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	stage_id int,
	match_id varchar(30) not null,
	id varchar(30) not null constraint games_pk primary key,
	octane_id int,
	"number" int,
	duration int,
	"date" timestamp,
	overtime bool,
	flip_ballchasing bool,
	ballchasing varchar(50),
	map_id varchar(30),
	map_name varchar(100),
	blue_winner bool,
	blue_team_id varchar(30),
	blue_shots int,
	blue_goals int,
	blue_saves int,
	blue_assists int,
	blue_score int,
	blue_shooting_percentage numeric,
	orange_team_id varchar(30),
	orange_shots int,
	orange_goals int,
	orange_saves int,
	orange_assists int,
	orange_score int,
	orange_shooting_percentage numeric,
	orange_winner bool,
	blue_ball_possession_time numeric,
	blue_ball_time_in_side numeric,
	blue_boost_bpm int,
	blue_boost_bcpm numeric,
	blue_boost_avg_amount numeric,
	blue_boost_amount_collected int,
	blue_boost_amount_stolen int,
	blue_boost_amount_collected_big int,
	blue_boost_amount_stolen_big int,
	blue_boost_amount_collected_small int,
	blue_boost_amount_stolen_small int,
	blue_boost_count_collected_big int,
	blue_boost_count_stolen_big int,
	blue_boost_count_collected_small int,
	blue_boost_count_stolen_small int,
	blue_boost_amount_overfill int,
	blue_boost_amount_overfill_stolen int,
	blue_boost_amount_used_while_supersonic int,
	blue_boost_time_zero_boost numeric,
	blue_boost_time_full_boost numeric,
	blue_boost_time_boost0_to25 numeric,
	blue_boost_time_boost25_to50 numeric,
	blue_boost_time_boost50_to75 numeric,
	blue_boost_time_boost75_to100 numeric,
	blue_movement_total_distance numeric,
	blue_movement_time_supersonic_speed numeric,
	blue_movement_time_boost_speed numeric,
	blue_movement_time_slow_speed numeric,
	blue_movement_time_ground numeric,
	blue_movement_time_low_air numeric,
	blue_movement_time_high_air numeric,
	blue_movement_time_powerslide numeric,
	blue_movement_count_powerslide int,
	blue_positioning_time_defensive_third numeric,
	blue_positioning_time_neutral_third numeric,
	blue_positioning_time_offensive_third numeric,
	blue_positioning_time_defensive_half numeric,
	blue_positioning_time_offensive_half numeric,
	blue_positioning_time_behind_ball numeric,
	blue_positioning_time_infront_ball numeric,
	blue_demo_inflicted int,
	blue_demo_taken int,
	orange_ball_possession_time numeric,
	orange_ball_time_in_side numeric,
	orange_boost_bpm int,
	orange_boost_bcpm numeric,
	orange_boost_avg_amount numeric,
	orange_boost_amount_collected int,
	orange_boost_amount_stolen int,
	orange_boost_amount_collected_big int,
	orange_boost_amount_stolen_big int,
	orange_boost_amount_collected_small int,
	orange_boost_amount_stolen_small int,
	orange_boost_count_collected_big int,
	orange_boost_count_stolen_big int,
	orange_boost_count_collected_small int,
	orange_boost_count_stolen_small int,
	orange_boost_amount_overfill int,
	orange_boost_amount_overfill_stolen int,
	orange_boost_amount_used_while_supersonic int,
	orange_boost_time_zero_boost numeric,
	orange_boost_time_full_boost numeric,
	orange_boost_time_boost0_to25 numeric,
	orange_boost_time_boost25_to50 numeric,
	orange_boost_time_boost50_to75 numeric,
	orange_boost_time_boost75_to100 numeric,
	orange_movement_total_distance numeric,
	orange_movement_time_supersonic_speed numeric,
	orange_movement_time_boost_speed numeric,
	orange_movement_time_slow_speed numeric,
	orange_movement_time_ground numeric,
	orange_movement_time_low_air numeric,
	orange_movement_time_high_air numeric,
	orange_movement_time_powerslide numeric,
	orange_movement_count_powerslide int,
	orange_positioning_time_defensive_third numeric,
	orange_positioning_time_neutral_third numeric,
	orange_positioning_time_offensive_third numeric,
	orange_positioning_time_defensive_half numeric,
	orange_positioning_time_offensive_half numeric,
	orange_positioning_time_behind_ball numeric,
	orange_positioning_time_infront_ball numeric,
	orange_demo_inflicted int,
	orange_demo_taken int,
	constraint games_event_fk
		foreign key(event_id)
			references rocket_league.events(id),
--	constraint games_stage_fk
--		foreign key(event_id, stage_id)
--			references rocket_league.events_stages(event_id, id),
	constraint games_match_fk
		foreign key(match_id)
			references rocket_league.matches(id)
);

create table rocket_league.games_players (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30),
	stage_id int,
	match_id varchar(30) not null,
	game_id varchar(30) not null,
	team_id varchar(30),
	color varchar(10) not null,
	id varchar(30) not null,
	shots int,
	goals int,
	saves int,
	assists int,
	score int,
	shooting_percentage numeric,
	advanced_goal_participation numeric,
	advanced_rating numeric,
	advanced_mvp bool,
	boost_bpm int,
	boost_bcpm numeric,
	boost_avg_amount numeric,
	boost_amount_collected int,
	boost_amount_stolen int,
	boost_amount_collected_big int,
	boost_amount_stolen_big int,
	boost_amount_collected_small int,
	boost_amount_stolen_small int,
	boost_count_collected_big int,
	boost_count_stolen_big int,
	boost_count_collected_small int,
	boost_count_stolen_small int,
	boost_amount_overfill int,
	boost_amount_overfill_stolen int,
	boost_amount_used_while_supersonic int,
	boost_time_zero_boost numeric,
	boost_percent_zero_boost numeric,
	boost_time_full_boost numeric,
	boost_percent_full_boost numeric,
	boost_time_boost0_to25 numeric,
	boost_time_boost25_to50 numeric,
	boost_time_boost50_to75 numeric,
	boost_time_boost75_to100 numeric,
	boost_percent_boost0_to25 numeric,
	boost_percent_boost25_to50 numeric,
	boost_percent_boost50_to75 numeric,
	boost_percent_boost75_to100 numeric,
	movement_avg_speed numeric,
	movement_total_distance numeric,
	movement_time_supersonic_speed numeric,
	movement_time_boost_speed numeric,
	movement_time_slow_speed numeric,
	movement_time_ground numeric,
	movement_time_low_air numeric,
	movement_time_high_air numeric,
	movement_time_powerslide numeric,
	movement_count_powerslide numeric,
	movement_avg_powerslide_duration numeric,
	movement_avg_speed_percentage numeric,
	movement_percent_slow_speed numeric,
	movement_percent_boost_speed numeric,
	movement_percent_supersonic_speed numeric,
	movement_percent_ground numeric,
	movement_percent_low_air numeric,
	movement_percent_high_air numeric,
	positioning_avg_distance_to_ball numeric,
	positioning_avg_distance_to_ball_possession numeric,
	positioning_avg_distance_to_ball_no_possession numeric,
	positioning_avg_distance_to_mates numeric,
	positioning_time_defensive_third numeric,
	positioning_time_neutral_third numeric,
	positioning_time_offensive_third numeric,
	positioning_time_defensive_half numeric,
	positioning_time_offensive_half numeric,
	positioning_time_behind_ball numeric,
	positioning_time_infront_ball numeric,
	positioning_time_most_back numeric,
	positioning_time_most_forward numeric,
	positioning_goals_against_while_last_defender int,
	positioning_time_closest_to_ball numeric,
	positioning_time_farthest_from_ball numeric,
	positioning_percent_defensive_third numeric,
	positioning_percent_offensive_third numeric,
	positioning_percent_neutral_third numeric,
	positioning_percent_defensive_half numeric,
	positioning_percent_offensive_half numeric,
	positioning_percent_behind_ball numeric,
	positioning_percent_infront_ball numeric,
	positioning_percent_most_back numeric,
	positioning_percent_most_forward numeric,
	positioning_percent_closest_to_ball numeric,
	positioning_percent_farthest_from_ball numeric,
	demo_inflicted int,
	demo_taken int,
	coach bool,
	substitute bool,
	constraint gameplayer_pk
		primary key (game_id, id),
	constraint gameplayer_event_fk
		foreign key(event_id)
			references rocket_league.events(id),
--	constraint gameplayer_stage_fk
--		foreign key(event_id, stage_id)
--			references rocket_league.events_stages(event_id, id),
	constraint gameplayer_match_fk
		foreign key(match_id)
			references rocket_league.matches(id),
	constraint gameplayer_game_fk
		foreign key(game_id)
			references rocket_league.games(id)
);