-- This code is written for Postgres

-- Events table
create table rocket_league.events (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	id varchar(30) not null constraint events_pk primary key,
	slug varchar not null,
	"name" varchar not null,
	start_date timestamp,
	end_date timestamp,
	region varchar(10),
	"mode" smallint,
	prize_amount int,
	prize_currency varchar(10),
	tier varchar(20),
	image varchar,
	"groups" varchar[]
);
	
-- Events stages table
create table rocket_league.events_stages (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	id int not null,
	"name" varchar not null,
	"format" varchar(20),
	region varchar(10),
	start_date timestamp,
	end_date timestamp,
	liquipedia varchar,
	prize_amount int,
	prize_currency varchar(10),
	qualifier bool,
	lan bool,
	location_venue varchar(100),
	location_city varchar(50),
	location_country varchar(10),
	constraint stages_pk
		primary key (event_id, id),
	constraint stages_fk
		foreign key(event_id)
			references rocket_league.events(id)
);


-- Matches table
create table rocket_league.matches (
	created_at timestamp not null default now(),
	updated_at timestamp not null default now(),
	event_id varchar(30) not null,
	stage_id int,
	id varchar(30) not null constraint matches_pk primary key,
	slug varchar not null,
	octane_id int,
	"date" timestamp,
	"format_type" varchar(50),
	"format_length" int,
	blue_games int,
	blue_winner bool,
	blue_team_id varchar(30),
	blue_shots int,
	blue_goals int,
	blue_saves int,
	blue_assists int,
	blue_score int,
	blue_shooting_percentage numeric,
	blue_boost_bpm int,
	blue_boost_bcpm numeric,
	blue_boost_avg_amount numeric,
	blue_boost_amount_collected int,
	blue_boost_amount_stolen int,
	blue_boost_amount_collected_big int,
	blue_boost_amount_stolen_big int,
	blue_boost_amount_collected_small int,
	blue_boost_amount_stolen_small int,
	blue_boost_count_collected_big int,
	blue_boost_count_stolen_big int,
	blue_boost_count_collected_small int,
	blue_boost_count_stolen_small int,
	blue_boost_amount_overfill int,
	blue_boost_amount_overfill_stolen int,
	blue_boost_amount_used_while_supersonic int,
	blue_boost_time_zero_boost numeric,
	blue_boost_time_full_boost numeric,
	blue_boost_time_boost0_to25 numeric,
	blue_boost_time_boost25_to50 numeric,
	blue_boost_time_boost50_to75 numeric,
	blue_boost_time_boost75_to100 numeric,
	blue_movement_total_distance numeric,
	blue_movement_time_supersonic_speed numeric,
	blue_movement_time_boost_speed numeric,
	blue_movement_time_slow_speed numeric,
	blue_movement_time_ground numeric,
	blue_movement_time_low_air numeric,
	blue_movement_time_high_air numeric,
	blue_movement_time_powerslide numeric,
	blue_movement_count_powerslide int,
	blue_positioning_time_defensive_third numeric,
	blue_positioning_time_neutral_third numeric,
	blue_positioning_time_offensive_third numeric,
	blue_positioning_time_defensive_half numeric,
	blue_positioning_time_offensive_half numeric,
	blue_positioning_time_behind_ball numeric,
	blue_positioning_time_infront_ball numeric,
	blue_demo_inflicted int,
	blue_demo_taken int,
	orange_games int,
	orange_winner bool,
	orange_team_id varchar(30),
	orange_shots int,
	orange_goals int,
	orange_saves int,
	orange_assists int,
	orange_score int,
	orange_shooting_percentage numeric,
	orange_boost_bpm int,
	orange_boost_bcpm numeric,
	orange_boost_avg_amount numeric,
	orange_boost_amount_collected int,
	orange_boost_amount_stolen int,
	orange_boost_amount_collected_big int,
	orange_boost_amount_stolen_big int,
	orange_boost_amount_collected_small int,
	orange_boost_amount_stolen_small int,
	orange_boost_count_collected_big int,
	orange_boost_count_stolen_big int,
	orange_boost_count_collected_small int,
	orange_boost_count_stolen_small int,
	orange_boost_amount_overfill int,
	orange_boost_amount_overfill_stolen int,
	orange_boost_amount_used_while_supersonic int,
	orange_boost_time_zero_boost numeric,
	orange_boost_time_full_boost numeric,
	orange_boost_time_boost0_to25 numeric,
	orange_boost_time_boost25_to50 numeric,
	orange_boost_time_boost50_to75 numeric,
	orange_boost_time_boost75_to100 numeric,
	orange_movement_total_distance numeric,
	orange_movement_time_supersonic_speed numeric,
	orange_movement_time_boost_speed numeric,
	orange_movement_time_slow_speed numeric,
	orange_movement_time_ground numeric,
	orange_movement_time_low_air numeric,
	orange_movement_time_high_air numeric,
	orange_movement_time_powerslide numeric,
	orange_movement_count_powerslide int,
	orange_positioning_time_defensive_third numeric,
	orange_positioning_time_neutral_third numeric,
	orange_positioning_time_offensive_third numeric,
	orange_positioning_time_defensive_half numeric,
	orange_positioning_time_offensive_half numeric,
	orange_positioning_time_behind_ball numeric,
	orange_positioning_time_infront_ball numeric,
	orange_demo_inflicted int,
	orange_demo_taken int,
	"number" int,
	reverse_sweep_attempt bool,
	reverse_sweep bool,
	constraint match_event_fk
		foreign key(event_id)
			references rocket_league.events(id)
--	constraint match_stage_fk
--		foreign key(event_id, stage_id)
--			references rocket_league.events_stages(event_id, id)
);
